language: node_js
node_js:
  - "10"
before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash
  - export PATH="$HOME/.yarn/bin:$PATH"
after_success:
  - yarn add gulp
  - gulp docs
  - gem install jekyll
  - cd ./docs/ && jekyll build
env:
  - secure: OXCVx+umyxvsBBAdDnliKggeeDI6+MJnH01DRz3MSwcG2WMUxtzxKtPL4t03t+wfTmCoGmEMFa8OO1UgwfOoAMNwrEQHPG/AfEnV5A67FKoKY56vUD3rkNcWV5V/IfmQzrYzQSjyjgs19RY+1sD7CKK75bQWYuAQOoNrIpb84gc=
sudo: false
deploy:
  provider: surge
  project: ./docs/
  domain: "$(echo $TRAVIS_REPO_SLUG | sed 's/\//-/g')-${TRAVIS_BRANCH}.surge.sh"
  skip_cleanup: true
  on:
    all_branches: true
